# Generated by Django 5.2.4 on 2025-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_users', '0002_remove_customuser_is_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
