# Generated by Django 5.2.4 on 2025-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_galaxy', '0003_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
