# Generated by Django 5.2.4 on 2025-07-17 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
